apiVersion: skaffold/v2beta17
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*
build: 
  local:  
    push: false
  #googleCloudBuild:
    #projectId: ticketing-296822
    #dockerImage: gcr.io/cloud-builders/docker
  artifacts:
   # - image: us.gcr.io/ticketing-296822/auth
    - image: tyler509/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: tylerg509/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: tylerg509/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .